### PR TITLE
Add module support to MappedReducer only

### PR DESCRIPTION
**Pull request by thomhos**
I added support for the MappedReducer to have initial state when you want to use it as part of a module structure.

The MappedPipeReducers still need to be done. @Rokt33r can you assist in this?

### CODE REVIEW

**Comment by Rokt33r** [comment]
Oh, sorry. Yes, I could!

**Comment by Rokt33r** [comment]
Great job! I'll merge it and publish the new release soon.

**Comment by Rokt33r** [comment]
Published!

**Comment by thomhos** [comment]
Awesome thanks, didn't know the implementation for the other reducers would be the same haha. Thanks for fixing!

**Pull request merged**
